//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilaLesaWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public Bookings()
        {
            this.BookingServices = new HashSet<BookingServices>();
        }
    
        public int BookingID { get; set; }
        public int CustomerID { get; set; }
        public int SiteID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public string Status { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Sites Sites { get; set; }
        public virtual ICollection<BookingServices> BookingServices { get; set; }
    }
}
