//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilaLesaWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerVisits
    {
        public int VisitID { get; set; }
        public int CustomerID { get; set; }
        public int SiteID { get; set; }
        public System.DateTime VisitStart { get; set; }
        public System.DateTime VisitEnd { get; set; }
        public string Notes { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Sites Sites { get; set; }
    }
}
