//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilaLesaWpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sites
    {
        public Sites()
        {
            this.Bookings = new HashSet<Bookings>();
            this.CustomerVisits = new HashSet<CustomerVisits>();
        }
    
        public int SiteID { get; set; }
        public string SiteCode { get; set; }
        public string SiteName { get; set; }
        public string SiteType { get; set; }
        public int Capacity { get; set; }
        public decimal PricePerNight { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual ICollection<CustomerVisits> CustomerVisits { get; set; }
    }
}
